apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ctlog-managectroots
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ctlog-managectroots
    app.kubernetes.io/part-of: scaffolding
  name: ctlog-managectroots
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: ctlog-managectroots
status:
  loadBalancer: {}
